### ISSUE TITLE
All methods return 'is not a function'

### ISSUE THREAD

**Issue by GreepTheSheep** [Treverix/custom-electron-titlebar#13] opened 2020-10-06 16:06 UTC
**Describe the bug**
When you call a method (either `updateBackground` or `updateTitle`) it shows 'is not a function'

**Screenshots**
![image](https://user-images.githubusercontent.com/42576124/95227526-7f137000-07fe-11eb-99c4-4e9759e69736.png)
![image](https://user-images.githubusercontent.com/42576124/95227562-8a669b80-07fe-11eb-98c3-87f197b33733.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Electron version 10.1.0
 - Node Version 12.16.3

**Comment by Treverix** [comment] 2020-10-06 20:46
I couldn't reproduce that. I added both method calls inside the example app (preload) and it changed title and background as expected. Please add more info to show how you used the library.

I see that you probably used it on the `render.js` script while the example application defines the titlebar on the `preload.js`.

**Comment by GreepTheSheep** [comment] 2020-10-06 20:57
yeah i put it in the `render.js` and i didn't know where to put it. I used a form to change the title in this screenshot and it calls the function ok() in the render file (linked with the HTML file)
So all methods should run in preload file ? And can IPCs run in preload file ? (I have a doubt about this)

**Comment by Treverix** [comment] 2020-10-06 21:08
Honestly, I never tried using the titlebar on a render script, I always used it with the preload. So I can't tell if or how it will work and what are benefits or limitations.

You could try creating the titlebar on the preload and adding it as `window.titlebar` to access it from the render script later.

IPC works fine on the preload. That's something I use always on my apps.

I close this ticket as it does not seem to be a bug or an issue.

**Closed as completed by Treverix** 2020-10-06 21:08 UTC
Labels: blocked/need-info

**Comment by GreepTheSheep** [comment] 2020-10-07 06:25
I think I need some help...
I called the function in the preload file. ipcMain was loaded from https://github.com/Treverix/remote
![image](https://user-images.githubusercontent.com/42576124/95294986-87a78d00-0876-11eb-8480-31bb7900c9cb.png)
But it return this in node console:
![image](https://user-images.githubusercontent.com/42576124/95294918-65157400-0876-11eb-94bc-436223bd2450.png)

**Comment by Treverix** [comment] 2020-10-07 14:36
`ipcMain` is for the main process, you need to use `ipcRender` on preload and render scripts. If you want to send a message from the render to the preload script via ipc, then you could try to
- send a message from render to the backend (`ipcRender.invoke('title-updated', 'new title)`)
- fetch the message here and push it back to the render process (`ipcMain.handle('title-updated', (e, title) => {webContents.send('titlebar-update-title', title)}`
- fetch the new message on the preload script (`ipcRenderer.on('titlebar-update-title', (e, title) => {titleBar.updateTitle(title)})`

As a rough idea, not sure if the syntax is 100% OK.

Otherwise, as I suggested, try adding the `titlebar` reference to `window` or `document` to use it on the render script also.
